# Generated by Django 6.0.3 on 2026-04-03 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_review_stars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
